spring:
  application:
    name: triple-work-api
  config:
    activate:
      on-profile: test
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
server:
  port: 8080
---
spring:
  application:
    name: triple-work-api
  config:
    activate:
      on-profile: development
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
server:
  port: 3000
---
spring:
  application:
    name: triple-work-api
  config:
    activate:
      on-profile: production
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
