spring:
  application:
    name: triple-work-api
  config:
    activate:
      on-profile: test
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
springdoc:
  paths-to-match:
    - /v1//cities/**
    - /v1//trips/**
    - /v1//users/**
server:
  port: 8080
---
spring:
  application:
    name: triple-work-api
  config:
    activate:
      on-profile: development
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
  sql:
    init:
      data-locations: classpath:data.sql
      mode: always
springdoc:
  paths-to-match:
    - /v1//cities/**
    - /v1//trips/**
    - /v1//users/**
server:
  port: 3000
---
spring:
  application:
    name: triple-work-api
  config:
    activate:
      on-profile: production
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: false
    defer-datasource-initialization: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Triple?serverTimezone=UTC&useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
    username: root
    password:
springdoc:
  paths-to-match:
    - /v1//cities/**
    - /v1//trips/**
    - /v1//users/**
